name: shubham_weather
description: "Handcrafted by Shubham Bane"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^11.2.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  weather: ^3.1.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_no_internet_widget: ^1.0.0+18-dev.1
  lottie: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appLogo.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/appLogo.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/appLogo.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/appLogo.png"

flutter_native_splash:
  color: "#000000"
  image: assets/appLogo.png
  branding: assets/appLogo.png
  color_dark: "#000000"
  image_dark: assets/appLogo.png
  branding_dark: assets/appLogo.png

  android_12:
    image: assets/appLogo.png
    icon_background_color: "#000000"
    image_dark: assets/appLogo.png
    icon_background_color_dark: "#000000"

  web: false

flutter:

  uses-material-design: true

  assets:
    - assets/